from pydantic import BaseModel, Field

class QuestionRequest(BaseModel):
    question: str = Field(..., description="User's question for the AI agent")

class AnswerResponse(BaseModel):
    answer: str = Field(..., description="Response generated by the AI agent")
