services:
  app:
    container_name: agentic-app
    build:
      context: ../
      dockerfile: agentic_mlflow_article/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=https://9h6vlw9n-5001.uks1.devtunnels.ms/
    volumes:
      - ../agentic_mlflow_article/app:/app/app:rw
      - mlruns:/mlruns

    # env_file:
    #   - .env

  mlflow:
    container_name: agentic-mlflow
    image: ghcr.io/mlflow/mlflow:v3.1.0
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_ARTIFACT_ROOT=/mlruns
    volumes:
      - mlruns:/mlruns
    # env_file:
    #   - .env

volumes:
  app-code:
  mlruns:
